### ISSUE TITLE
Too much runtime spent on logging

### ISSUE THREAD

**Issue by mbrdl** [jplag/JPlag#1004]
I did some runtime profiling, and it turns out that JPlag spends about 20% of its runtime on logging, to be more precise, on line 49 in `AbstractComparisonStrategy.java`:
```java
logger.info("Comparing {}-{}: {}", first.getName(), second.getName(), comparison.similarity());
```
I would argue for removing this line. A more sophisticated approach would be disabling it depending on the size of the input.

I think for a tool as mature as JPlag the logging to console should be much more minimal in general but that's another issue.

**Comment by tsaglam** [comment]
This is indeed an issue. I also know why this is the case. The similarity method makes some calculations _each time_ it when called. This was probably not implemented differently since it was unclear that this was called more than once per comparison. However,  This can be fixed by either calculating it on the creation of the comparison just when the function is called once.

[This line](https://github.com/jplag/JPlag/blob/284206ce766e5175cf4aeeddbded63494a105d0e/core/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java#LL51C9-L51C102) leads to the method being called a second time.

**Comment by mbrdl** [comment]
Relatedly, about 5% of the runtime is spent on`Integer.valueOf(1)` in line 216 of JPlagOption. Probably should be expected that with quadratic runtime, such small things can come to make up a sigificant portion.

**Comment by mbrdl** [comment]
Seems like the runtime profiling misled me here, I measured the runtime difference at only about 5%:
<img width="293" alt="Screenshot 2023-04-14 at 19 08 15" src="https://user-images.githubusercontent.com/50548929/232111234-5d5f3d32-5452-480c-a6dd-adcc57726db0.png">
Each row represents 100 runs. I'll close the issue for now, but logging is still a topic that could be worth looking into.
