### ISSUE TITLE
Add logging library and rethink error collection

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#117]
Instead of direct prints to the console, a logging library shall be used.

EDIT:

- [x] Add logging library
- [x] Replace all occurence of Syso/Syserr
- [ ] Remove error consumer interface and rethink error collection

**Comment by tsaglam** [comment]
Through recent improvements (#234 and #241), the `Program` interface was replaced by the `ErrorConsumer` interface, which would be a starting point whenever the legacy error reporting is replaced with a modern logging library.

**Comment by tsaglam** [comment]
Currently, all errors are shown at the end of all comparisons in order to give the users an aggregated overview of what went wrong. Especially for large datasets this we cannot just print errors when they appear and then let the user scroll through endless messages to find the errors. Thus, we need to retain this feature when replacing the current system with a logging library.
