### ISSUE TITLE
Enhance overall code quality

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#119]
There is a major restructuring effort left, even after the v3.0.0 release. This includes:
- [x] Rework JPlag options
- [x] Rework Greedy String Tiling class
- [x] Rework exit exception (moved to #245)
- [x] Clean JPlag class

**Comment by Alberth289346** [comment]
Yesterday I fixed a bug in path handling, and ran into lots of opportunities to refactor

- There are "experimental" features in there, they need a decision whether to keep them or delete them imho.
- There are "hidden options", I'd say either make them unhidden or delete them.
- There is an "emphirical stduy" in there.
- There is a "distr" variable in `Options` denoting a person that got a copy.
- Filter code drags in the Text frontend
- Heaps and heaps of arrays where a `List<>` class would suffice (code was likely written in Java 1 I guess)
- Code uses `Vector<>` which is synchronized, Java docs say to prefer `ArrayList<>` for non-synchronized use.
- `printAllLanguages()` needs a `Program` instance to instantiate a language which is near impossible to get there.

**Comment by tsaglam** [comment]
Thanks for the comprehensive list! I assume you work on a fork of yours based on the legacy version of JPlag. Is that correct?
Some of these issues might have been already refactored (e.g. experimental features and hidden options are gone), however, I am going to check if some of these issues are still open issues in the current v3.0.0 pre-release state.

**Comment by Alberth289346** [comment]
Apparently I have an old version indeed ( fbded8822d02c852fdc017e225a3d036fe417285 which is of May 2020). You did a lot of new work there!

I am extending jplag with a frontend for a declarative automaton language to see if we can use the program.
Being declarative, code is very high level, very few details you can drop. Any change is very soon a "structural" change (swapping declarations or automata).
I tried having having many separated sections, assuming jplag would understand that many small matching sections is also a big blob of code, but it seems it searches for one consecutive big blob. We're still finding out if that is sufficient.

A bit of experiences:

At Java level, I failed to understand how to get the code in Eclipse for editing, so I ended with a copy of a merged source. (There was no documentation at all how to interface, so I needed to jump through source to read code, and for that I need the code in an editor that understands it's one project in many small pieces.)

We also have our own parser, and it's not based on antlr. Trying to use our tokens failed as jplag used more code from antlr, so I now parse the input, and then make a copy of the token list to antlr-style tokens. I had some fun with too small and too large indices as our line and column numbers are different from apparent expected values in `jplag.Token`.

I had some trouble with paths too that I fixed locally, but perhaps that got fixed in all the new changes.

**Comment by tsaglam** [comment]
> I am extending jplag with a frontend for a declarative automaton language to see if we can use the program.
> Being declarative, code is very high level, very few details you can drop. Any change is very soon a "structural" change (swapping declarations or automata). I tried having having many separated sections, assuming jplag would understand that many small matching sections is also a big blob of code, but it seems it searches for one consecutive big blob. We're still finding out if that is sufficient.

I am not sure if I understand your problems correctly, but you may try to adapt the min token match. Each frontend defines the default min token match value and you can also overwrite that via the corresponding CLI parameter. Reducing the min token match value will lead to JPlag requiring fewer consecutive tokens to match in order to count it as an identical section.

> At Java level, I failed to understand how to get the code in Eclipse for editing, so I ended with a copy of a merged source. (There was no documentation at all how to interface, so I needed to jump through source to read code, and for that I need the code in an editor that understands it's one project in many small pieces.)

In Eclipse you can import JPlag with `File > Import > Maven > Existing Maven Projects`. You can also use IntelliJ if you prefer that.

> We also have our own parser, and it's not based on antlr. Trying to use our tokens failed as jplag used more code from antlr, so I now parse the input, and then make a copy of the token list to antlr-style tokens. I had some fun with too small and too large indices as our line and column numbers are different from apparent expected values in `jplag.Token`.

Language frontends do not need to be based on antlr. For example, the Java 9+ frontend is not.
They just need to implement the interfaces from the [frontend-utils](https://github.com/jplag/jplag/tree/master/jplag.frontend-utils/src/main/java/jplag).

> I had some trouble with paths too that I fixed locally, but perhaps that got fixed in all the new changes.

If you have a specific problem with paths, please open up an issue about that and describe the issue in detail. Then we can try to fix it.

I hope I could help!
