### ISSUE TITLE
Add support for newer java features

### ISSUE THREAD

**Issue by sebinside** [jplag/jplag#120]
A new or updated java language frontend shall be added which supports newer features like lambdas, switches, records, etc. This could, e.g., work with the next Java LTS version.

**Comment by tsaglam** [comment]
With JPlag legacy I can parse newer Java features, however with with the current 3.0.0 pre-release I get an error: `Error: Not enough valid submissions! (found 0 valid submissions)`. Thus this might not even be a problem with the `Java9` frontend, as it could be a general bug caused by the rework. Source code: [NewJavaFeatures.zip](https://github.com/jplag/jplag/files/6800136/NewJavaFeatures.zip)

We should also work on the error reporting, as this message is not specific enough.

**Comment by tsaglam** [comment]
The maven compiler level determines what source files the JavaC compiler can read. As the Java 9+ frontend uses the JavaC API, this affects what JPlag can parse.

**Comment by tsaglam** [comment]
Addressed by #159.
