### ISSUE TITLE
Unable to analyze submissions with too small base code

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#161]
Empty test files seem to break the analysis.

See:
https://github.com/ls1intum/Artemis/issues/3603#issuecomment-883182921
https://github.com/ls1intum/Artemis/issues/3603#issuecomment-883185327

**Comment by tsaglam** [comment]
JPlag throws an `ExitException` if the basecode is smaller than the specified min token match. Note that these tiny basecodes will not work due to the fact how the similarity calculation is implemented. Even when removing the check that throws the `ExitException`, the results of the comparison will be as if no basecode was used at all.

**Comment by tsaglam** [comment]
When the basecode is smaller than the min token match, it would not be detected as a match anyways, thus making the basecode obsolete. With the recent improvements to error messages, I think it is acceptable to close this issue.
