### ISSUE TITLE
JPlagOptions are modified during the execution

### ISSUE THREAD

**Issue by tsaglam** [jplag/JPlag#274]
After passing an options instance to JPlag, some changes are made to the options instance.
This includes but is not limited to:
- Setting the language
- Setting language defaults
- Passing excluded file names

This is convoluting for new developers and may lead to maintenance issues further down the road. We should treat it as a record, and not modify option instances after they are configured. This would require storing parameters determined during the execution of JPlag separately.

**Comment by GabrielL** [comment]
There is another issue with `JPLagOptions`: *everything* depends on it! most of the classes don't need the full options, only one or two fields. It would be better to pass them directly, to avoid the dependency. This will allow to test the separate pieces separately.

From what I see, the cli driver for the code is:

* CLI
* JPlag
* SubmissionSetBuilder
* other small classes like JPlagOptions, Verbosity, etc…

Nothing should depend on this, maybe except `Report`, as it is "legacier" than the rest, and probably need the options for reporting purpose.

For things like Language or the excluded file names, this is already hold inside `JPlag`, just passing them into the report should be fine (see #272  https://github.com/GabrielL/JPlag/blob/languages-as-spi/jplag/src/main/java/de/jplag/CLI.java#L59 for example with Language)

The real issue would be `minimumTokenMatch` and `fileSuffixes`, since it comes from the cli and the language default configuration. It is not used for the moment by `Report`, but I am guessing that the information will be relayed in the new json formatted output.

For reporting purpose, it could be possible to create an ad-hoc object that will contain every relevant parameters, already process and ready to be consumed.

**Comment by GabrielL** [comment]
Since I am looking into the different options, 2 question arise:
* Is the `hasBaseCode` option is really necessary in `GreedyStringTiling` ? https://github.com/jplag/JPlag/blob/master/jplag/src/main/java/de/jplag/GreedyStringTiling.java#L224. From what I understand, `token.basecode` can only be true if `hasBaseCode()` is also true.
* In `Submission`/`SubmissionSet`, why do we care about `isdebugParser()` ? https://github.com/jplag/JPlag/blob/master/jplag/src/main/java/de/jplag/Submission.java#L176. It seems to me that this copies the non parsable files. Maybe better error reporting could simply describe what are those files, instead of trying to copy them elsewhere ?

**Comment by tsaglam** [comment]
> * Is the `hasBaseCode` option is really necessary in `GreedyStringTiling` ? https://github.com/jplag/JPlag/blob/master/jplag/src/main/java/de/jplag/GreedyStringTiling.java#L224. From what I understand, `token.basecode` can only be true if `hasBaseCode()` is also true.

I would assume that you are right, but we kept it in there until we can be sure (#193 will help with that). While we dramatically improved the core code with large-scale overhauls, the greedy string tiling is still very confusing so we are extra careful with that in order to not introduce any bugs. But we can make an issue for this and might be able to get rid of the options call there in the future.

> * In `Submission`/`SubmissionSet`, why do we care about `isdebugParser()` ? https://github.com/jplag/JPlag/blob/master/jplag/src/main/java/de/jplag/Submission.java#L176. It seems to me that this copies the non parsable files. Maybe better error reporting could simply describe what are those files, instead of trying to copy them elsewhere ?

For large data-sets is better to persist invalid submissions instead of just reporting that in the very long CLI output.
For this, we have this "debug"-option (`-d`). Even if not every user might need this, we should keep that feature for those who do.

**Comment by tsaglam** [comment]
Addressed in #572.
