### ISSUE TITLE
Not able to build JPlag with python 3.0  

### ISSUE THREAD

**Issue by Faraznomani** [jplag/jplag#32]
1)you can not build jplag using `mvn clean generate-sources assembly:assembly`,
as the repository POM file is pointing to (i.e. http://bob.ipd.uni-karlsruhe.de/nexus/content/repositories/public/ ) does not has pythom jar or pom files.

Specifically, this folder does not have python folder,
http://bob.ipd.uni-karlsruhe.de/nexus/content/repositories/public/edu/kit/ipd/jplag/
which breaks the building process, with the error:

> [ERROR] Failed to execute goal on project jplag: Could not resolve dependencies for project edu.kit.ipd.jplag:jplag:jar:2.11.9-SNAPSHOT: Failure to find edu.kit.ipd.jplag:python-3:jar:0.0.1-SNAPSHOT in http://bob.ipd.uni-karlsruhe.de/nexus/content/repositories/public/ was cached in the local repository, resolution will not be reattempted until the update interval of ipdNexus has elapsed or updates are forced -> [Help 1]

2) The second error is because of a wrong version, during the built, it points for maven pulgins at [proguard-maven-plugin/2.10.11/ ](http://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.10.11/) which shows 404 Not Found Error. But I think the version needed is [proguard-maven-plugin/2.0.11/ ](http://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.0.11/)

I wanted to change the max output range from 1,000. But after doing so I am not able to build it again.
I changed the maven plugin link to the one I have mentioned above, and also commented Python dependency from main POM file then i was able to build successfully.

Please update the broken links and also add python in the repository.

**Comment by lama0206** [comment]
Dear Faraznomani

1) You can build jplag from sources as all internal dependencies are included as source code. I'm not sure why the build did not work for you.

2) I've deployed the compiled modules to our repository so this should fix the problem for now - but because of 1) this shouldn't be needed anyways.

3) Thanks for pointing out the incorrect proguard version. As this plugin is not used, this should not be a problem either. Anyways, its fixed in master now.

Thanks,
Mathias
