### ISSUE TITLE
Add support for Visual Basic

### ISSUE THREAD

**Issue by lama0206** [jplag/JPlag#5]

**Comment by u-riaz** [comment]
Hi,
I'm interested in adding support for VBA (subset of VB). I had a detailed look on how to add new front-end. Can someone please help me in the following queries:
1. Can i extend some existing frontend (C#, C++ etc.) which is more closer/similar to VB? If yes, which will be more closer and how should i proceed.
2. VB is ANTLR based or javac based? Or it's a programmer choice to select one of two?
3. Can anyone work (help) with me to add this VB support?
 Please pinpoint any additional issues/points which should be considered for front-end addition.
Thanks !

**Comment by lama0206** [comment]
Hi

In short:
1. No. A front-end reads code (the students' solutions) and outputs token streams. JPlag then compares these token streams. There isn't much you could recycle from a different front-end. The abstract front-end classes provide more or less everything you need.
2. Whether to use antlr or javacc does not depend on the language you want to support. What you need is a grammar of VB - and its up to you whether you use antlr or javacc. Just search for a VB grammar and then use whatever parser that grammar was written for.

Regards
Mathias

**Comment by u-riaz** [comment]
Hi, thanks Mathias for your helping reply.

I had found VB grammar (https://github.com/antlr/grammars-v4/tree/master/vb6) as well as VBA grammar (https://github.com/retailcoder/grammars-v4/tree/master/vba). These are antlr based.
Please guide me either following 3 steps are right (I'm following ../jplag.frontend.java-1.2/Readme.txt) ?
1. Having grammar.g4, i'll choose token types to be generated (for VBA codes) and would define them in Token.java and TokenConstants.java.
2. Then, I would add appropriate actions in the grammar.g4 e.g . "parser.add(...". 
3. Appropriate changes in other files, if needed.
I'm asking this because jplag.frontend.java-1.2 is ANTLR-2.7.7 based and vba grammar is ANTLR v4. So, would this path work in VBA-ANTLR-v4 case?

Next query is, having the VBA frontend ready, how can i test its correctness, means either it's generating tokens correctly or not, without using "mvn". Means, how should i build and install jplag (without mvn compile), so that it takes vba files as input and report their similarity as text file(s). 

Thanks

**Comment by lama0206** [comment]
You should take a look at java-1.7 as it uses an antlr4 grammar. It also contains a main method that reads a file and prints the source code and the tokens produced by the front-end that is very helpful when testing the front-end.

If the front-end provides tokens for all "important" parts of the source file, you can use jplag to compare two or more vba files.

**Comment by u-riaz** [comment]
Hi Mathias, hope you'll be fine.
Mathias, thanks for your recommendation of looking java-17, now probably i'm in a position of writing vba frontend by following these steps:
1. get vba grammar and use ANTLR's jar file to generate necessary files e.g. VBAListner.java, VBAParser.java etc.
2. Having ANTLR's generated files, edit java-17-frondend's files (from jplag sub directories) and make them work for vba source files (i think, i just have to register Listeners on appropriate grammar entry/exit points to generate chosen tokens).
3.Having the frontend ready, i can put it into jplag dir, re-build whole project and can enjoy VBA support. 
I'm right ?

But that's not what i actually want :(
My end-goals are
1. Get tokens for each VBA source file.
2. Use these tokens with jplag's main algo (Greedy String Tiling), to get a similarity score for each pair in a text file.
I don't want jplag's webservice or other facilities it offers (hyperlinks to see matched code etc.). In short i just want similarity score as a value between 0-100, nothing else.
As, jplag's whole project (available from Github) is too complex, i don't want to dig-down in all details because it would be very time consuming and out of my scope.
So, can you please guide me how should i proceed? Can you people have simple stand-alone implementation of main algo without any webservices etc. ?
Helps would be greatly appreciated.. !
Thanks !
Regards:
Usman

**Comment by lama0206** [comment]
There is a stand-alone version of JPlag. The web service forwards requests to that binary anyway.

The main JPlag program is in the jplag directory and the main class is implemented in the file jplag/jplag/src/main/java/jplag/JPlag.java. Jplag will generate a html report without further modifiactions. You just have to provide the vba front-end.

**Comment by u-riaz** [comment]
Hi Mathias,
I'm done with VBA front-end. Now i'm getting tokens like Loop_Begin, Module_Begin, If_else, xyz_stmt and so on..
Next step is to find similarity among these. Understanding whole Jplag system and then making suitable changes seeming too difficulty. So, i planned to implement my own version of GSTiling in python. Regarding this, i have some queries:
1. in call gsTiling(String A, String B); what actually both strings A,B contain? Either whole tokens (i.e. Loop_Begin, Module_Begin etc.) or single character representation for each token like a->Loop_Begin ans so on..
2. If strings contain single character for each token, then how Jplag converts token-strings to char? Means, there is some systematic approach or just a unique mapping for each token i.e all Loop_Begin will be mapped to 'a', If_else will be mapped to 'b' , and so on..
3. how to define "MinimumMatchLength"  (a lower bound for the length of a match) ?

Thanks

**Comment by lama0206** [comment]
Sorry, I do not understand. If you have the frontend, there's nothing left do to. Just tell Jplag to use your frontend and you're done.

**Comment by tsaglam** [comment]
Closed, as the current frontend plans go in other directions. If somebody is interested in building such a frontend I can reopen this issue. If somebody already has built a working front-end we can always add it, so feel free to open up a PR.

**Comment by tsaglam** [comment]
Closed, as the current frontend plans go in other directions. If somebody is interested in building such a frontend I can reopen this issue. If somebody already has built a working front-end we can always add it, so feel free to open up a PR.
