### ISSUE TITLE
Problemas con la ejecución de jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by LauraBachiller** [jplag/jplag#59]
hola buenas! 

Tengo varios problemas con este programa ya que primero intente descargarme la version 2.11.9 pero resulta  que solo encuentro el 2.11.8, porque hay una que pone 2.11.9 pero cuando la descargas resulta que es la 2.11.8 ( lo pongo aqui porque soy nueva en git hub y no se como comentar algo que haya subido otra persona). 
Aparte de esto, al no poder acceder a la 2.11.9 he decidido usar la que tengo disponible que es la 2.11.8, pero no se como emplear el comando -bc. Yo lo que quiero hacer es con -bc poner un archivo base de codigo, y  con este comparar todos los archivos que tenga guardados en otra carpeta. 

¿Como podria hacer esto posible?

Muchas gracias.

**Comment by lama0206** [comment]
Hey Laura

Sorry, my Spanish is way worse than yours so I answer in English.

Jplag is built to compare different solutions (e.g., written by different students) with each other. We say that we identify plagiarism if we detect commonalities between two solutions. The parameter -bc should be used if you supply the students with source code to start from (say, a skeleton implementation or some framework or base code). Jplag will take this base code and ignore matches between two solutions that come from this base code. So from what google translate tells me, this is not what you want to do.

* If you have one directory (with several files) per student, put the directories in one directory so that you can run Jplag on this root directory (this is the default). You should have, for example, root-dir/student1/<some files> and root-dir/student2/<some files>
* If you have one file per student, use the -c option and list all files that you want to compare. For example, jplag -c base.java student1.java student2.java

Does that answer your question?

Best,
lama

**Comment by LauraBachiller** [comment]
Hi Lama,

Well, i try to speak in english. 

With Jplag I want to compare several files that i have in one directory with only one file, i mean that i want to compare por example 50 files with another 1 but not between the 50 files. Is this possible with Jplag? 

My purpose is to use jpag as a correction tool.

Thanks,
Laura

**Comment by weigelt** [comment]
Hi Laura,

you can't compare one file to 50 other files directly.
I see two options for your case:

1. do 50 one-to-one comparisons with the -c option: jplag -c base.java student1.java, jplag -c base.java student2.java and so on (However, that's a time killer).
2. use jplag as recommended and only look at the comparison to your base file in the results.

Best whishes
Sebastian
