### ISSUE TITLE
Report Viewer does not show matches properly

### ISSUE THREAD

**Issue by sebinside** [jplag/JPlag#658]
The current version of the Report Viewer displays matches only if the corresponding files are inside the root folder (e.g., in this example here: [result-working.zip](https://github.com/jplag/JPlag/files/9536410/result-working.zip)). If they are in subfolders (e.g., in this example in submission A: [result-notworking.zip](https://github.com/jplag/JPlag/files/9536409/result-notworking.zip)), they are not resolved properly.

A little debugging showed the underlying problem: Matches are represented with their full path, i.e. `subfolder/SimpleDuplicate.java` in the matches map. File names (that are used in the viewer to query the matches), are represented by their name only, i.e. `SimpleDuplicate.java`.

As I don't know which parts of the viewer depend on which type of file representation, I did not change it but rather hope for the help of @nestabentum 😄 

Screenshot of the bug:
![image](https://user-images.githubusercontent.com/7331248/189379320-1f2b1346-55e6-4e8b-ae10-b12f81d8827a.png)

**Comment by nestabentum** [comment]
Oh, I oversaw this issue, sorry. Currently, I'm pretty swamped, could take a look at this next week, though.

**Comment by nestabentum** [comment]
Do we want  the title of a nested file to indicate the nesting by being named `subfolder/Matches.java` or do we prefer `Matches.java`?

<img width="492" alt="image" src="https://user-images.githubusercontent.com/33717535/192085536-c6e5e252-2909-4137-b32f-dff37d5aeebc.png">

Deep nesting could lead to long titles introducing the need to abbreviate: `../subfolder/Matches.java`. 
Also noteworthy: the submission name generated by JPlag is platform-dependent as it contains the platform-specific folder separator.

**Comment by tsaglam** [comment]
> Do we want the title of a nested file to indicate the nesting by being named `subfolder/Matches.java` or do we prefer `Matches.java`?

`subfolder/Matches.java` is better I think, at least if we abbreviate for long paths.

> Also noteworthy: the submission name generated by JPlag is platform-dependent as it contains the platform-specific folder separator.

Ah, interesting, but makes sense. @sebinside @JanWittler That should still work with the recent/planned changes, right?

**Comment by nestabentum** [comment]
I fear the solution to this problem is not as trivial as I hoped...

The names of the files in a match are determined via `Token#getFile` in `ComparisonReportWriter#convertMatchToReportMatch`. `Token#file` is set by the language model's parser. 
From my/the report viewer's pov this name is chosen arbitrarily. As it happens, the java language model names the file `subfolder/Matches.java` when it is located in a subfolder.

The `Submission` class has a list of `Files`. These Files are Java's standard representation of a File. While the name of `File#getName` equals the name of `Token#getFile` in the case of top-level files in the Java language model, this seems to be rather a coincidence than design. To reliably solve this issue, a link between `Token` ad JPlag's file representation has to be established.

**Comment by JanWittler** [comment]
> To reliably solve this issue, a link between Token ad JPlag's file representation has to be established.

In #688 , I refactored `Token#getFile` to type `File` and already integrated a solution to store the file path relative to the submission's root directory. Storing the file path relative to the submission's root was chosen to preserve the previous implicit output. However, if you need another file path representation, it should now be possible to adjust that one method instead of having to care about language frontends. I hope this makes fixing the problem way easier?

https://github.com/jplag/JPlag/blob/b72c4e505e09a45f7b8bb8b2450ef588e0245d2b/core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java#L101-L108

> Ah, interesting, but makes sense. @sebinside @JanWittler That should still work with the recent/planned changes, right?

We should aim to generate a platform-independent JSON (i.e. by ensuring a unix file separator and adapting paths during decoding back to the current OS) but for now it doesn't break anything I would say.

**Comment by sebinside** [comment]
After a quick look, hopefully, @JanWittler changes should be making it easier. Also, I would second platform-independent paths, unix-style. If it's easily possible to not only take the relative path from the root directory, but even include the root directories name, this could also solve issue 3 from #686 for free.

**Comment by sebinside** [comment]
This issue has been replaced by #710.
