### ISSUE TITLE
Fix result generation for Java 1.7

### ISSUE THREAD

**Issue by lama0206** [jplag/JPlag#8]

**Comment by u-riaz** [comment]
Hi,
I want to get generated tokens list, for this i tried to enable "-v lp" option, so that i can get all outputs/messages to console. But i'm getting the following error.
Error: Unknown option: -v
The whole command is " java -jar jplag-2.11.8-SNAPSHOT-jar-with-dependencies.jar  -v lp -l java17 -r results/ java-codes/ "
Can you please have a look. 
Additionally, how can i get the generated token list on a separate text-file for each submission? 
Thanks

**Comment by tsaglam** [comment]
Closed, as the Java 1.7 frontend is no longer part of this project.
