### ISSUE TITLE
Python3 syntactically incorrect programs are not included

### ISSUE THREAD

**Issue by tskowal** [jplag/jplag#80]
A Python3 program with any syntactical error is not included in comparisons which is very annoying. If you have a class in which some students attempted to copy and modify programs, but made some mistake, it might not be detected.

As a matter of fact, if syntactically incorrect programs were included, the same front end would work reasonably well for Python2 programs.

**Comment by tskowal** [comment]
I understand it won't be fixed? Pity! It's a very common problem.

**Comment by tsaglam** [comment]
The problem lies in how JPlag works at its core. It detects plagiarism based on parsed tokens of the code. The problem is, if a parser for a language cannot parse the code, it cannot work. If the code has syntax errors, the parser will probably fail. In JPlag, the Python parser is based on a ANTLR grammar (see https://github.com/jplag/jplag/tree/master/jplag.frontend.python-3). This grammar is responsible for what can be parsed and what can't. If you want, you can contribute to that language frontend end improve its parsing capabilities. We, however, cannot rewrite how JPlag works at its core.
